import { type NextPage } from 'next';
import Head from 'next/head';
import PageTemplate from '../../templates/PageTemplate.page';

import { useRouter } from 'next/router';
import React from 'react';
import ArticleCard from '../../components/ArticleCard/ArticleCard';
import Loading from '../../components/LoadingContainer/Article/Loading';
import { useArticle } from '../../pages/api/hooks';

const Article: NextPage = () => {
  const { query } = useRouter();

  console.log(query);

  const { article, status } = useArticle(
    query['article-id'] as unknown as number
  );

  console.log(status);
  console.log(article);

  if (status === 'loading') {
    return (
      <PageTemplate>
        <Head>
          <title>Article</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mt-2">
          <div className="flex justify-center space-x-0 mdtb:space-x-4 ">
            <div className="hidden h-auto w-64 flex-none space-y-4 mdtb:inline">
              <div> SIDE MENU </div>
            </div>
            <div className="w-m h-auto flex-auto space-y-4 mdtb:m-0">
              <Loading />
            </div>
            <div className="hidden h-auto w-80 flex-none space-y-4 lg:inline">
              <div>RIGHT CARDS</div>
            </div>
          </div>
        </div>
      </PageTemplate>
    );
  }

  if (status === '404') {
    return (
      <PageTemplate>
        <Head>
          <title>Article</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mt-2">
          <div className="flex justify-center space-x-0 mdtb:space-x-4 ">
            <div className="hidden h-auto w-64 flex-none space-y-4 mdtb:inline">
              <div> SIDE MENU </div>
            </div>
            <div className="w-m h-auto max-w-3xl flex-auto space-y-4 mdtb:m-0">
              <h2>Cannot find article</h2>
            </div>
            <div className="hidden h-auto w-80 flex-none space-y-4 lg:inline">
              <div>RIGHT CARDS</div>
            </div>
          </div>
        </div>
      </PageTemplate>
    );
  }

  if (!article) {
    return null;
  }

  return (
    <PageTemplate>
      <>
        <Head>
          <title>{article.title}</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mt-2">
          <div className="flex justify-center space-x-0 mdtb:space-x-4 ">
            <div className="hidden h-auto w-64 flex-none space-y-4 mdtb:inline">
              <div> SIDE MENU </div>
            </div>
            <div className="w-m h-auto max-w-3xl flex-auto space-y-4 mdtb:m-0">
              <ArticleCard
                isFeatured={true}
                isMainArticle={true}
                author={article.user.name}
                profileImage={article.user.profile_image_90}
                featureImage={article.social_image}
                date={article.published_timestamp}
                tags={article.tags}
                body={article.body_html}
                title={article.title}
                readingTime={article.reading_time_minutes}
                reactionCount={article.public_reactions_count}
              />
            </div>
            <div className="hidden h-auto w-80 flex-none space-y-4 lg:inline">
              <div>RIGHT CARDS</div>
            </div>
          </div>
        </div>
      </>
    </PageTemplate>
  );
};

export default Article;
