import { type NextPage } from 'next';
import Head from 'next/head';
import ArticlesSection from '../components/ArticlesSection/ArticlesSection';
import PageTemplate from '../templates/PageTemplate';

const Home: NextPage = () => {
  return (
    <PageTemplate>
      <>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mt-16">
          <div className="flex justify-center space-x-0 mdtb:space-x-4 ">
            <div className="hidden h-auto w-64 flex-none space-y-4 mdtb:inline">
              <div> SIDE MENU </div>
            </div>
            <div className="w-m h-auto max-w-2xl flex-auto space-y-4 mdtb:m-0">
              <ArticlesSection />
            </div>
            <div className="hidden h-auto w-80 flex-none space-y-4 lg:inline">
              <div>RIGHT CARDS</div>
            </div>
          </div>
        </div>
      </>
    </PageTemplate>
  );
};

export default Home;
